### PR TITLE
Lots of clean up + a bit of WI

### PR DESCRIPTION
**Pull request by mark-i-m**
- Removed old drafts, blog, posts, etc from template
- Made things a bit more wisconsin by adding some red....

### CODE REVIEW

**Comment by mark-i-m** [comment]
Content should be the same...

It looks like this:

Screenshot_2019-04-16 SACM

**Comment by jsajal** [comment]
@mark-i-m can you change the settings of the your forked repo and allow it to build as a github page. I would like to have a live view of the changes. It's difficult to gauge from the screenshot put above.

**Comment by mark-i-m** [comment]
Unfortunately, I can't because I am already publishing a site from another repo

**Comment by mark-i-m** [comment]
@jsajal You can try it out by cloning my branch and running jekyll locally (see the readme I added).

**Comment by jsajal** [comment]
Good Comments : - I like the red theme and thanks a lot for all the code cleanup, that was long overdue.

Some Suggestions :- 

1. Don't make the whole top bar/navigation panel red, its a bit overwhelming as it is bright red, instead make it red whenever anyone hovers over it or rather clicks on any of the option.

2. The footer color of light grey is not a good combination with red links, it gives it a very dull outlook, I agree that even the earlier color was not good but this is something that can be experimented upon.

3. Now the final and the main suggestion. HomePage of any website is supposed to be  concise, where it's main aim is to give the user an overarching view of the whole website and is a bit embellished to capture the user visiting the website. There are two problems with using a list based design. First, I as a user has to scroll to read the important stuffs which gives it a feel of a blog (plus the font size is too big and overwhelming, but that is another issue). Second, the primary reason, I chose a widget based design in the first place is of three folds, first you can put small pictures on the widget to embellish the homepage a bit (which also tells the user something about the information in that widget, for eg a picture of a TGIF tells the user of the overall outlook of TGIF), second it keeps the content aligned by assigning appropriate font sizes and spacing, third it keeps the homepage concise  by displaying the important information. When you use a list based design it is essentially same as what SACM had earlier, just the colors and font size have changed, so it defeats the purpose of redesigning the website and presenting a new outlook.


Lastly - "SACM does a bunch of stuff that you might not know about…", I like this line but such lines should never be on the homepage as it doesn't portray the professional outlook of the organization (even though we do fun activities but in the end we are a prof organization). Rather should be included in the About page.

All of the things that I have mentioned above are some design choices/principles. However nothing is perfect and everything related to the website can be brainstormed further. Once again thank you for all the code cleanup :)

**Comment by mark-i-m** [comment]
@jsajal Thanks for the feedback. I have updated according to your comments. It is still hosted at the same location if you want to play around with it.

> Don't make the whole top bar/navigation panel red

I inverted.

> The footer color of light grey is not a good combination with red links, it gives it a very dull outlook, I agree that even the earlier color was not good but this is something that can be experimented upon.

Yeah, I agree... I tried to improve, but it is a bit hard. What do you think now?

> Now the final and the main suggestion

I vaguely agree with you, but here I am a bit biased because I use my monitors in portrait mode. On my screen, the current home page looks cramped and busy, and it doesn't format properly because it requires a wide screen. If we want to use this layout, I would suggest limiting to only 2 columns at most. It probably also makes sense to make better use of the navbar (e.g. the Miscellaneous stuff doesn't need to be on the homepage, I think). I have made such changes in the latest commits.

> (even though we do fun activities but in the end we are a prof organization).

Lol, I've never thought of us as a professional organization. CS is not for professionals IMHO; it is for creatives. "Professionals" go to engineering departments instead :stuck_out_tongue: 

In all seriousness, I would like to push back on this. I don't think we should try to portray SACM as a professional org; it is a student org that gives people relief from the seriousness of work. I feel like that care-free nature should be emphasized more.

Nonetheless, I have removed the sentence because it messes up the formatting with columns.

**Comment by jsajal** [comment]
@mark-i-m I saw the changes.

1. The top bar looks amazing now. (Misc has found its appropriate place now)
2. For the footer we will have to still think of something
3. Just one more suggestion can you align the two columns on homepage (both the images and text), and also reduce the font size and size of images a bit (again both are overwhelming), otherwise it looks great now. If it's too much work, let me know I will handle it.

4. _(Lol, I've never thought of us as a professional organization. CS is not for professionals IMHO; it is for creatives. "Professionals" go to engineering departments instead 😛_)
        I think of it as "professional creativity" 😛 , but jokes aside ,I might not have been able to portray what I meant , what I meant was not the professionality of the organization but a professional nature of website designing (I still think I am not able to portray it correctly, spare me). Yes SACM is also a fun org in my opinion too.
All of the quirky stuff is necessary for the website but they are ideally meant for inside pages, like I have lot of quirky and fun ideas in displaying each of our teams on the officers page (like Top Brass 😛 ), but thats for another day, lets chat sometime and play around with more fun ideas. 

If we still want to put something on the homepage, we need to come up with a better tagline :)

**Comment by mark-i-m** [comment]
Sounds good :)

I will make the changes tomorrow.

**Comment by mark-i-m** [comment]
Updated :)

**Comment by jsajal** [comment]
@mark-i-m Thank you, it looks good now!

**Pull request merged**
